Rgb ctrl
KuzmenkoNikita/ESTC-main-project pull request #13
Opened 2021-11-21 18:46 UTC by KuzmenkoNikita

2021-11-24 07:33 UTC, Diadlo requested changes

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +#define COUNTOF_WORKMODES   3
Вроде эти константы не используются

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +#define WAIT_APPLY_PARAM            100
Почему у прошлой константы есть размерность `_MS`, а тут нет?

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +        *peCurrentWM  = EWM_TUNING_H;
Почему после V идет H? Должен быть NO_INPUT

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +    if(*peCurrentWM == EWM_TUNING_V)
Что если добавить еще один режим? У нас ведь `EWM_TUNING_V` применяется в разных значениях. Как реальный режим и как последний элемент. Если добавить новое значение в конец, то надо пройтись по коду и обновить только те места, где он используется в качестве последнего. Поэтому часто в ENUM добавляют значение `XXX_LAST` которое по значению равно последнему элементу или `XXX_COUNT` который на 1 больше последнего элемента. Это позволяет разделять места, где нужен конкретный режим и последний.

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +        if(psHSV->S > 100)
Во-первых, изначально подразумевался не выжок до 0, а изменение направления, но это ладно
Во-вторых, у вас 3 очень похожих ветки. Подумайте на счет выделения их в функцию. Типа `get_next_with_rotate`

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +    else
Большинство стандартов кодирования требуют симметричное использование скобок. Т.е. если if или else имеет блок со скобками, то второй тоже должен быть со скобками.
Ну или в данном случае `else` можно убрать т.к. на этом функция заканчивается и `return` там не имеет смысла

2021-11-24 07:33 UTC, Diadlo commented on Project/main.c
> +    if(eWM == EWM_TUNING_H)
Мне кажется вместо `if ... else if` тут `switch` хорошо бы подошел, т.к. идет перебор по значениям enum. Но в целом используйте на ваш вкус

2021-11-24 07:35 UTC, Diadlo commented on Project/main.c
> +            nrf_delay_ms(10);
Кажется уже говорил об этом раньше, но будьте осторожнее с задержками такого рода. Они влияют на исполнение программы в целом. Если в ней задач будет становится много, то такая задержка может быть критична для каких-то модулей

2021-11-28 09:43 UTC, KuzmenkoNikita commented on Project/main.c
> +#define COUNTOF_WORKMODES   3
Fixed

2021-11-28 09:45 UTC, KuzmenkoNikita commented on Project/main.c
> +#define WAIT_APPLY_PARAM            100
Fixed

2021-11-28 10:27 UTC, KuzmenkoNikita commented on Project/main.c
> +    if(*peCurrentWM == EWM_TUNING_V)
Fixed

2021-11-28 10:27 UTC, KuzmenkoNikita commented on Project/main.c
> +        *peCurrentWM  = EWM_TUNING_H;
Fixed

2021-11-28 10:27 UTC, KuzmenkoNikita commented on Project/main.c
> +    else
Fixed

2021-11-28 10:53 UTC, KuzmenkoNikita commented on Project/main.c
> +        if(psHSV->S > 100)
Fixed

2021-11-28 10:54 UTC, KuzmenkoNikita commented on Project/main.c
> +    if(eWM == EWM_TUNING_H)
Fixed

2021-11-28 10:58 UTC, KuzmenkoNikita commented on Project/main.c
> +            nrf_delay_ms(10);
На данный момент это единственная задержка в проекте. Пока оставлю ее, но буду иметь ввиду, что в дальнейшем, возможно ее необходимо будет перенести в таймер

2021-11-28 11:01 UTC, closed without merging